//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.08 at 02:47:16 PM CST 
//


package compiler;

import javax.xml.bind.annotation.XmlRegistry;

import com.next.schema.table.Column;
import com.next.schema.table.ObjectFactory;
import com.next.schema.table.Table;



@XmlRegistry
public class ObjectFactoryImpl extends ObjectFactory
{
	@Override
    public Column createColumn() 
    {
        return new ColumnImpl();
    }
	@Override
    public Table createTable() {
        return new TableImpl();
    }

}
