insert into ORDR(Id,BpId,DocStatus) values(-9,-1,'O');
insert into ORDR(Id,BpId,DocStatus) values(-8,-2,'C');
insert into RDR1(Id,LineId,ParentId) values(-1,0,-1);
insert into RDR1(Id,LineId,ParentId) values(-2,1,-1);
insert into RDR1(Id,LineId,ParentId) values(-3,0,-2);
insert into RDR1(Id,LineId,ParentId) values(-4,1,-2);
insert into OCRD(Id,CardCode) values(-1,'C001');
insert into OCRD(Id,CardCode) values(-2,'C002');
insert into OCRD(Id,CardCode) values(-3,'C003');
